### PR TITLE
11 Detect additional Fields

### PR DESCRIPTION
**Pull request by gkowalski**
Added to the following types to the identification  of  the physical address annotations  : 

- City
- Country
- other
- state
- street

The country list was pulled from the [internet](https://raw.githubusercontent.com/datasets/country-list/master/data.csv).
The other lists were pulled from the 2014 i2b2 challenge data set by searching for the corresponding tags in the gold standard and using those values. The various text for each was then stored in corresponding CSV files within the data directory. When the app is called to identify these types, the lists are used to regex against to the incoming note text in a case insensitive fashion to make the matches.

### CODE REVIEW

**Comment by tschaffter** [comment]
@gkowalski 

- [ ] Can you please describe in the first message of this PR the strategy that you came up with?
- [ ] There is slight format inconsistency regarding the usage of surround quotes. Can you make so that all data files use surrounding quotes in the same way.

**Comment by tschaffter** [comment]
> The other lists were pulled from the 2014 i2b2 challenge data set by searching for the corresponding tags in the gold standard and using those values.

There are one main issue with this approach:

- Information about the i2b2 dataset is leaked.
  - We are not allowed to release i2b2 data
  - Developers could use this knowledge to submit algorithms that will have a biased performance on the i2b2 dataset

**Comment by tschaffter** [comment]
> Developers could use this knowledge to submit algorithms that will have a biased performance on the i2b2 dataset

This is actually less critical than initially thought since developers can access the i2b2 dataset on the official web page.

**Comment by gkowalski** [comment]
I missed the documentation on what the final test data set was going to be . Where is that ?

**Comment by tschaffter** [comment]
At launch we will use the evaluation set of the i2b2 dataset for evaluation and keep the training set for when we will enable training in 2021. The data used by this method should be independent of the data of the i2b2 dataset as well as any prior knowledge that we may have of this dataset, so that the performance of this example method is not biased when evaluated on the i2b2 dataset.

EDIT: The above paragraph is my original though to have 1) an example method that is not unnecessary coupled to a given dataset and 2) reasoning with the model-to-data framework that we are using where even training data is not released to the developers. However, in the context of the i2b2 challenge in 2014, it would not have been wrong for the organizers of the challenge to create an example method that uses data from the training set since the participant will do the same. But in the NLP Sandbox, we are interested in benchmarking the generalization of the performance on multiple datasets that we will add starting next year. In this context, I would prefer us to adopt a more general approach for the example methods.

**Comment by tschaffter** [comment]
One cool source of information could be to use [Google BigQuery](https://cloud.google.com/bigquery) if you have used it in the past (I haven't). Otherwise, I'm sure that we can find data sample from other legit sources.

**Comment by tschaffter** [comment]
We could also use regex and the data that we currently have (country and zip code).
https://www.regexpal.com/93592

Example:

- <number> ... <street|avenue|...> ... <state> ... <country>
- <number> ... <street|avenue|...> ... <state>
- <number> ... <street|avenue|...>

In order to be considered valid, we could require that the annotation detected is no longer than N words (e.g. 10)?

**Comment by tschaffter** [comment]
@gkowalski 

- Please update the description of the PR to reflect the latest changes.
  - Please give a reference for all the source of data that you are adding with this PR

**Comment by tschaffter** [comment]
If you have a chance, please comment on my idea to use regex to detect addresses.

**Review by tschaffter — APPROVED** [review]
That's good for now. I'll fill in the blank as you are currently on vacations. Thanks!

**Pull request merged**
